'use client';
import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownUp, ArrowUpRight, Bookmark, Check, ChevronDown, ChevronRight, CircleHelp, Copy, ExternalLink, Layers, Pause, Radar, RefreshCw, Search, ShieldCheck, SlidersHorizontal, TrendingUp, X, Zap } from 'lucide-react';
import { matchEvent, compareDetailed, marketLabels, type MarketKind, type PinEvent, type PinMarket, type Opportunity, type Sport } from '@/lib/radar';
import { getEvents, getExpandedEvent } from '@/lib/protocol';

type Health = { name:string;state:'waiting'|'running'|'done'|'error'|'partial'|'unavailable';events:number;matched:number;checked:number;markets:number;readMarkets:number;missing:number;byKind:Partial<Record<MarketKind,number>>;error?:string };
const fallback:Sport[]=[{key:'football',name:'Piłka nożna',icon:'⚽',pinnacleId:null,active:0},{key:'basketball',name:'Koszykówka',icon:'🏀',pinnacleId:null,active:0},{key:'tennis',name:'Tenis',icon:'🎾',pinnacleId:null,active:0},{key:'ice_hockey',name:'Hokej',icon:'🏒',pinnacleId:null,active:0},{key:'volleyball',name:'Siatkówka',icon:'🏐',pinnacleId:null,active:0}];
const number=(n:number,d=2)=>n.toLocaleString('pl-PL',{minimumFractionDigits:d,maximumFractionDigits:d});
const time=(date:string)=>new Date(date).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
const stateLabel:Record<Health['state'],string>={waiting:'W kolejce',running:'Skanowanie',done:'Sprawdzono',error:'Błąd źródła',partial:'Częściowy odczyt',unavailable:'Brak wspólnej oferty'};
const demoRows:Opportunity[]=[
 {id:'demo1',sport:'basketball',event:'Boston Celtics – Miami Heat',league:'NBA · przykład',start:'2026-10-10T00:00:00Z',market:'Zwycięzca meczu',pick:'Boston Celtics',odds:2.1,reference:1.91,fair:2,probability:.5,ev:5,observedAt:0,referenceAt:0,eventId:0,pinId:0,referenceOdds:[1.91,1.91],settlement:'Cały mecz, z dogrywką'},
 {id:'demo2',sport:'football',event:'Arsenal – Chelsea',league:'Premier League · przykład',start:'2026-10-10T16:00:00Z',market:'Wynik meczu',pick:'Arsenal',odds:2.4,reference:2.2,fair:2.2*(1/2.2+1/3.6+1/3.4),probability:(1/2.2)/(1/2.2+1/3.6+1/3.4),ev:(2.4/(2.2*(1/2.2+1/3.6+1/3.4))-1)*100,observedAt:0,referenceAt:0,eventId:0,pinId:0,referenceOdds:[2.2,3.6,3.4],settlement:'Czas regulaminowy · 1/X/2'},
 {id:'demo3',sport:'football',event:'Arsenal – Chelsea',league:'Premier League · przykład',start:'2026-10-10T16:00:00Z',market:'Gole Powyżej/Poniżej',pick:'Powyżej 2,5',odds:2.14,reference:1.91,fair:2,probability:.5,ev:7,observedAt:0,referenceAt:0,eventId:0,pinId:0,referenceOdds:[1.91,1.91],settlement:'Czas regulaminowy',kind:'total',period:'full'},
 {id:'demo4',sport:'basketball',event:'Boston Celtics – Miami Heat',league:'NBA · przykład',start:'2026-10-10T00:00:00Z',market:'Wynik handicap – 1. kwarta',pick:'Boston Celtics (−3,5)',odds:2.08,reference:1.91,fair:2,probability:.5,ev:4,observedAt:0,referenceAt:0,eventId:0,pinId:0,referenceOdds:[1.91,1.91],settlement:'1. kwarta',kind:'handicap',period:'q1'},
 {id:'demo5',sport:'football',event:'Arsenal – Chelsea',league:'Premier League · przykład',start:'2026-10-10T16:00:00Z',market:'Rzuty rożne – 1. połowa',pick:'Poniżej 4,5',odds:2.12,reference:1.91,fair:2,probability:.5,ev:6,observedAt:0,referenceAt:0,eventId:0,pinId:0,referenceOdds:[1.91,1.91],settlement:'1. połowa',kind:'corners',period:'h1'},
];
async function api<T>(path:string,signal?:AbortSignal):Promise<T>{const r=await fetch(path,{signal:signal??AbortSignal.timeout(45000)});const d=await r.json() as T&{error?:string};if(!r.ok)throw new Error(d.error||'Nie udało się pobrać danych');return d;}

export default function Home(){
 const [sports,setSports]=useState<Sport[]>(fallback),[sport,setSport]=useState('all'),[rows,setRows]=useState<Opportunity[]>([]),[health,setHealth]=useState<Record<string,Health>>({}),[running,setRunning]=useState(false),[error,setError]=useState(''),[current,setCurrent]=useState(''),[lastScan,setLastScan]=useState<number|null>(null),[auto,setAuto]=useState(true),[demo,setDemo]=useState(false),[query,setQuery]=useState(''),[marketFilter,setMarketFilter]=useState('all'),[periodFilter,setPeriodFilter]=useState('all'),[minEv,setMinEv]=useState(0),[minOdds,setMinOdds]=useState(''),[maxOdds,setMaxOdds]=useState(''),[sort,setSort]=useState('ev'),[favoriteOnly,setFavoriteOnly]=useState(false),[saved,setSaved]=useState<string[]>([]),[moreSports,setMoreSports]=useState(false),[modal,setModal]=useState<Opportunity|null>(null),[info,setInfo]=useState(false),[filters,setFilters]=useState(false),[budget,setBudget]=useState(100),[tax,setTax]=useState(0),[toast,setToast]=useState(''),[now,setNow]=useState(Date.now()),[mobileNav,setMobileNav]=useState(false);
 const control=useRef<AbortController|null>(null),mounted=useRef(false),runningRef=useRef(false),autoRef=useRef(true),timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const scanRef=useRef<()=>Promise<void>>(async()=>{});
 function message(text:string){setToast(text);setTimeout(()=>setToast(''),2600);}
 function save(id:string){setSaved(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem('easybet-favorites',JSON.stringify(next));return next;});}
 function update(key:string,patch:Partial<Health>){setHealth(old=>({...old,[key]:{...old[key],...patch}}));}
 async function start(){
  if(runningRef.current)return; runningRef.current=true;setRunning(true);setError('');setRows([]);setLastScan(null);const controller=new AbortController();control.current=controller;
  try {
   const data=await api<{sports:Sport[]}>('/api/sports',controller.signal);const list:Sport[]=data.sports;setSports(list);
   const initial:Record<string,Health>={};list.forEach(s=>initial[s.key]={name:s.name,state:s.pinnacleId&&s.active?'waiting':'unavailable',events:0,matched:0,checked:0,markets:0,readMarkets:0,missing:0,byKind:{}});setHealth(initial);
   // Scan every available sport independently of the display filter.
   for(const s of [...list].sort((a,b)=>Number(b.key==='basketball')-Number(a.key==='basketball'))){
    if(controller.signal.aborted)break;if(!s.pinnacleId||!s.active)continue;setCurrent(s.name);update(s.key,{state:'running'});
    let offset=0,events=0,matched=0,checked=0,markets=0,readMarkets=0,missing=0,pages=0,partial=false,partialError='';const byKind:Partial<Record<MarketKind,number>>={};const seen=new Set<number>();const pageIds=new Set<number>();
    try{
     let ref=await api<{events:PinEvent[];markets:PinMarket[];observedAt:number}>(`/api/reference?sport=${encodeURIComponent(s.key)}`,controller.signal);
     while(!controller.signal.aborted){
      const sourceEvents=await getEvents(s.key,offset,controller.signal);
      const inventory={pairs:sourceEvents.filter(b=>!!matchEvent(b,ref.events)).map(b=>({id:b.id})),firstId:sourceEvents[0]?.id||null,events:sourceEvents.length,next:sourceEvents.length>=40?offset+40:null};
      if(inventory.firstId&&pageIds.has(inventory.firstId)){partial=true;break;}if(inventory.firstId)pageIds.add(inventory.firstId);
      const fresh: {id:number}[]=inventory.pairs.filter((p:{id:number})=>!seen.has(p.id));fresh.forEach(p=>seen.add(p.id));
      events+=inventory.events;matched+=fresh.length;update(s.key,{events,matched});
      for(let i=0;i<fresh.length;i+=2){if(controller.signal.aborted)break;
       if(Date.now()-ref.observedAt>120000)ref=await api<{events:PinEvent[];markets:PinMarket[];observedAt:number}>(`/api/reference?sport=${encodeURIComponent(s.key)}`,controller.signal);
       const result={checked:0,markets:0,readMarkets:0,missing:0,byKind:{} as Partial<Record<MarketKind,number>>,errors:[] as string[],rows:[] as Opportunity[]};
       await Promise.all(fresh.slice(i,i+2).map(async pair=>{try{const b=await getExpandedEvent(pair.id,controller.signal);const p=matchEvent(b,ref.events);if(b.errors?.length)result.errors.push(...b.errors);if(p){const compared=compareDetailed(b,p,ref.markets,s.key,ref.observedAt,ref.events);result.rows.push(...compared.rows);result.markets+=compared.stats.matched;result.readMarkets+=compared.stats.read;result.missing+=compared.stats.missing;for(const [kind,count] of Object.entries(compared.stats.byKind))result.byKind[kind as MarketKind]=(result.byKind[kind as MarketKind]||0)+(count||0);result.checked++;}}catch(e){result.errors.push(e instanceof Error?e.message:'Błąd Betclic');}}));
       checked+=result.checked;markets+=result.markets;readMarkets+=result.readMarkets;missing+=result.missing;for(const [kind,count] of Object.entries(result.byKind))byKind[kind as MarketKind]=(byKind[kind as MarketKind]||0)+(count||0);if(result.errors.length){partial=true;partialError=result.errors[0];}
       setRows(old=>{const map=new Map(old.map(x=>[x.id,x]));result.rows.forEach((x:Opportunity)=>map.set(x.id,x));return [...map.values()];});update(s.key,{checked,markets,readMarkets,missing,byKind:{...byKind}});
      }
      pages++;if(inventory.next===null)break;
      if(pages>=50){partial=true;break;}offset=inventory.next;
     }
     update(s.key,{state:controller.signal.aborted?'partial':partial?'partial':'done',error:partial?partialError||'Nie wszystkie strony oferty udało się odczytać.':''});
    }catch(e){if(controller.signal.aborted)break;update(s.key,{state:'error',error:e instanceof Error?e.message:'Błąd źródła'});}
   }
   if(!controller.signal.aborted)setLastScan(Date.now());
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Nie udało się rozpocząć skanowania');}
  finally{if(controller.signal.aborted)setHealth(old=>Object.fromEntries(Object.entries(old).map(([k,v])=>[k,v.state==='running'||v.state==='waiting'?{...v,state:'partial',error:'Skanowanie zatrzymane.'}:v])));runningRef.current=false;setRunning(false);setCurrent('');control.current=null;}
 }
 scanRef.current=start;
 useEffect(()=>{
  if(mounted.current)return;mounted.current=true;
  try{setSaved(JSON.parse(localStorage.getItem('easybet-favorites')||'[]'));}catch{}
  const initial=setTimeout(()=>void scanRef.current(),0);timer.current=setInterval(()=>{setNow(Date.now());if(autoRef.current&&!runningRef.current&&document.visibilityState==='visible')void scanRef.current();},300000);
  const clock=setInterval(()=>setNow(Date.now()),15000);
  return()=>{clearTimeout(initial);control.current?.abort();if(timer.current)clearInterval(timer.current);clearInterval(clock);mounted.current=false;};
 },[]);
 const fresh=rows.filter(r=>now-r.observedAt<=300000&&now-r.referenceAt<=300000&&Date.parse(r.start)>now);
 const shown=(demo?demoRows:fresh).filter(r=>(sport==='all'||r.sport===sport)&&(marketFilter==='all'||(r.kind||'winner')===marketFilter)&&(periodFilter==='all'||(periodFilter==='full'?(r.period||'full')==='full':(r.period||'full')!=='full'))&&(!favoriteOnly||saved.includes(r.id))&&r.ev>=minEv&&(!minOdds||r.odds>=Number(minOdds))&&(!maxOdds||r.odds<=Number(maxOdds))&&`${r.event} ${r.pick} ${r.league} ${r.market}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='start'?Date.parse(a.start)-Date.parse(b.start):sort==='odds'?b.odds-a.odds:b.ev-a.ev);
 const statuses=Object.values(health),checked=statuses.reduce((a,s)=>a+s.checked,0),events=statuses.reduce((a,s)=>a+s.events,0),done=statuses.filter(s=>s.state==='done').length,finished=statuses.filter(s=>['done','error','partial'].includes(s.state)).length,marketCount=statuses.reduce((a,s)=>a+s.markets,0),readMarketCount=statuses.reduce((a,s)=>a+s.readMarkets,0),missingCount=statuses.reduce((a,s)=>a+s.missing,0),available=statuses.filter(s=>s.state!=='unavailable').length;
 const best=fresh.length?Math.max(...fresh.map(x=>x.ev)):null;
 const sourceErrors=statuses.filter(x=>x.state==='error'||x.state==='partial').length;
 const getSport=(key:string)=>sports.find(s=>s.key===key)||fallback.find(s=>s.key===key);
 const ev=modal?(modal.probability*modal.odds*(1-tax/100)-1)*100:0;
 const navSport=(key:string)=>{setSport(key);setFavoriteOnly(false);setMobileNav(false);};
 return <div className="app-shell">
  <aside className={`sidebar ${mobileNav?'opened':''}`}>
   <a className="brand" href="/"><span className="brand-icon"><Zap size={21} fill="currentColor"/></span><span>EASY<span className="mint">BET</span><small>VALUE RADAR</small></span></a>
   <div className="workspace"><span className="workspace-avatar">E</span><div>Twój radar<small>Betclic PL × Pinnacle</small></div><ChevronDown size={15}/></div>
   <div className="nav-title">PANEL</div>
   <button className={`nav-item ${!favoriteOnly?'active':''}`} onClick={()=>{setFavoriteOnly(false);setMobileNav(false);}}><Radar size={18}/><span>Valuebety</span><b>{fresh.length}</b></button>
   <button className={`nav-item ${favoriteOnly?'active':''}`} onClick={()=>{setFavoriteOnly(true);setMobileNav(false);}}><Bookmark size={18}/><span>Zapisane</span><b>{saved.length}</b></button>
   <button className="nav-item" onClick={()=>setInfo(true)}><CircleHelp size={18}/><span>Jak działa radar</span></button>
   <div className="nav-title sports-heading">SPORTY <span>{sports.length}</span></div>
   <button className={`sport-item ${sport==='all'?'selected':''}`} onClick={()=>navSport('all')}><Layers size={16}/><span>Wszystkie sporty</span><span className="sport-count">{fresh.length}</span></button>
   {(moreSports?sports:sports.slice(0,7)).map(s=><button key={s.key} className={`sport-item ${sport===s.key?'selected':''}`} onClick={()=>navSport(s.key)}><span className="sport-icon">{s.icon}</span><span>{s.name}</span><span className="sport-count">{fresh.filter(r=>r.sport===s.key).length||'–'}</span></button>)}
   <button className="more-sports" onClick={()=>setMoreSports(!moreSports)}>{moreSports?'Zwiń listę':'Pokaż wszystkie sporty'}<ChevronDown size={14} className={moreSports?'rotate':''}/></button>
   <div className="sidebar-bottom"><div className="source-label"><span className="dot"/>Źródła bez kredytów</div><p>Publiczne kursy Betclic i Pinnacle. Bez płatnego klucza API.</p><button onClick={()=>setInfo(true)}>O danych i pokryciu <ArrowUpRight size={14}/></button></div>
  </aside>
  <div className="main-wrap">
   <header className="topbar"><button className="mobile-menu icon-button" aria-label="Otwórz menu sportów" onClick={()=>setMobileNav(!mobileNav)}><Layers size={20}/></button><div className="breadcrumb">Panel <ChevronRight size={14}/><strong>{favoriteOnly?'Zapisane':'Valuebety'}</strong></div><div className="top-right"><span className="timezone">Czas: Polska</span><span className="private-pill"><ShieldCheck size={13}/> Panel valuebetów</span><button className="avatar" onClick={()=>setInfo(true)} aria-label="Informacje o panelu">E</button></div></header>
   <main>
    <div className="page-heading"><div><div className="eyebrow"><span className="tiny-line"/> TWOJA PRZEWAGA W KURSACH</div><h1>{favoriteOnly?'Zapisane okazje':'Value Radar'}<span className="beta">BETA</span></h1><p>Wyniki, sumy, handicapy i części meczu. Betclic PL × Pinnacle.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>setDemo(!demo)}><Layers size={15}/>{demo?'Wróć do danych':'Podgląd wyglądu'}</button><button className="primary" onClick={()=>running?control.current?.abort():void start()}>{running?<Pause size={15}/>:<RefreshCw size={15}/>} {running?'Zatrzymaj':'Skanuj teraz'}</button></div></div>
    <div className="intro-band"><div className="radar-art"><span/><span/><span/><Radar size={38}/></div><div><span className="intro-kicker">MNIEJ SZUKANIA. WIĘCEJ KONKRETÓW.</span><h2>Zobacz, gdzie kurs daje przewagę.</h2><p>Tylko dodatnie, szacowane EV dla zgodnych rynków przedmeczowych.</p></div><div className="band-tag"><span className="dot"/><span>BETCLIC PL <b>×</b> PINNACLE</span><small>Bez kredytów API</small></div></div>
    <div className="metrics">
     <div className="metric"><span>Aktywne valuebety <TrendingUp size={17}/></span><strong>{fresh.length}<small>EV &gt; 0%</small></strong><p>Świeże dane z obu źródeł</p></div>
     <div className="metric"><span>Najwyższe EV <Zap size={17}/></span><strong className="mint">{best===null?'—':`+${number(best)}%`}</strong><p>Wartość szacowana, przed kosztami</p></div>
     <div className="metric"><span>Dopasowane linie <Layers size={17}/></span><strong>{marketCount.toLocaleString('pl-PL')}</strong><p>{checked} odczytanych meczów · {events.toLocaleString('pl-PL')} wydarzeń</p></div>
     <div className="metric"><span>Sporty sprawdzone <Activity size={17}/></span><strong>{done}<small>/ {available||'—'}</small></strong><p>{running?`Teraz: ${current||'łączenie…'}`:lastScan?`Ostatni skan ${new Date(lastScan).toLocaleTimeString('pl-PL')}`:'Oczekiwanie na odczyt'}</p></div>
    </div>
    {demo&&<div className="notice demo"><Layers size={17}/><div><strong>Podgląd wyglądu — dane przykładowe.</strong> Te mecze i kursy służą wyłącznie demonstracji. Nie są sygnałami do obstawiania.</div><button onClick={()=>setDemo(false)} aria-label="Zamknij podgląd"><X size={17}/></button></div>}
    {error&&<div className="notice warning"><Activity size={17}/><div><strong>Nie udało się połączyć ze źródłem.</strong> {error}. Spróbuj ponownie przyciskiem „Skanuj teraz”.</div></div>}
    {!error&&sourceErrors>0&&<div className="notice warning"><Activity size={17}/><div>Część odczytów jest niepełna ({sourceErrors} {sourceErrors===1?'sport':'sportów'}). Szczegóły znajdziesz w statusie skanera.</div></div>}
    <div className="content-grid">
     <section className="opportunities panel"><div className="panel-heading"><div><h2>{favoriteOnly?'Zapisane valuebety':'Wykryte valuebety'}<span className="counter">{shown.length}</span></h2><p>{demo?'Przykłady interfejsu':'Identyczna linia, okres meczu i zasady rozliczenia'}</p></div><button className="icon-button" aria-label="Informacje o obliczeniach EV" onClick={()=>setInfo(true)}><CircleHelp size={17}/></button></div>
      <div className="filter-bar"><label className="search"><Search size={16}/><input aria-label="Szukaj meczu, ligi lub typu" placeholder="Szukaj meczu, ligi lub typu…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Wyczyść wyszukiwanie" onClick={()=>setQuery('')}><X size={13}/></button>}</label><button className={`filter-button ${filters?'pressed':''}`} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={15}/>Filtry{minEv>0||minOdds||maxOdds||marketFilter!=='all'||periodFilter!=='all'?<span className="filter-dot"/>:null}</button><label className="sort"><ArrowDownUp size={14}/><select aria-label="Sortowanie" value={sort} onChange={e=>setSort(e.target.value)}><option value="ev">Najwyższe EV</option><option value="start">Najbliższy mecz</option><option value="odds">Najwyższy kurs</option></select></label></div>
      {filters&&<div className="expanded-filters"><label>Rodzaj rynku<select value={marketFilter} onChange={e=>setMarketFilter(e.target.value)}><option value="all">Wszystkie rynki</option>{Object.entries(marketLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Okres<select value={periodFilter} onChange={e=>setPeriodFilter(e.target.value)}><option value="all">Cały mecz i części</option><option value="full">Cały mecz</option><option value="parts">Połowy / kwarty / sety</option></select></label><label>Minimalne EV (%)<input type="number" min="0" max="25" step="0.5" value={minEv} onChange={e=>setMinEv(Math.max(0,Number(e.target.value)))}/></label><label>Kurs od<input type="number" min="1" step="0.1" placeholder="1,01" value={minOdds} onChange={e=>setMinOdds(e.target.value)}/></label><label>Kurs do<input type="number" min="1" step="0.1" placeholder="Bez limitu" value={maxOdds} onChange={e=>setMaxOdds(e.target.value)}/></label><button onClick={()=>{setMinEv(0);setMinOdds('');setMaxOdds('');setQuery('');setSport('all');setMarketFilter('all');setPeriodFilter('all');}}>Wyczyść filtry</button></div>}
      <div className="sport-tabs"><button className={sport==='all'?'selected':''} onClick={()=>setSport('all')}>Wszystkie</button>{sports.slice(0,5).map(s=><button key={s.key} className={sport===s.key?'selected':''} onClick={()=>setSport(s.key)}>{s.icon} {s.name}</button>)}</div>
      {shown.length>0?<div className="table-scroll"><table><thead><tr><th>WYDARZENIE / TYP</th><th>BETCLIC</th><th>KURS FAIR</th><th>EV <span>↘</span></th><th aria-label="Akcje"/></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><div className="event-meta"><span>{getSport(r.sport)?.icon}</span>{r.league}<span>· {time(r.start)}</span></div><button className="event-name" onClick={()=>{setModal(r);setTax(0);}}>{r.event}</button><div className="pick-label"><span>{r.market}</span><b>{r.pick}</b></div></td><td><span className="odds betclic">{number(r.odds)}</span><small className="book-label">Betclic PL</small></td><td><span className="odds fair">{number(r.fair)}</span><small className="book-label">Pinnacle bez marży</small></td><td><button className="ev-chip" onClick={()=>{setModal(r);setTax(0);}}>+{number(r.ev)}%<ArrowUpRight size={12}/></button><small className="book-label">{demo?'Przykład':`${Math.max(0,Math.floor((now-r.observedAt)/60000))} min temu`}</small></td><td><button className={`icon-button bookmark ${saved.includes(r.id)?'is-saved':''}`} aria-label={saved.includes(r.id)?'Usuń z zapisanych':'Zapisz valuebet'} onClick={()=>save(r.id)}><Bookmark size={17} fill={saved.includes(r.id)?'currentColor':'none'}/></button></td></tr>)}</tbody></table></div>:<div className="empty-state"><div className={`empty-radar ${running&&!demo?'scanning':''}`}><Radar size={38}/></div><h3>{favoriteOnly?'Brak świeżych zapisanych okazji':query||sport!=='all'||minEv>0||minOdds||maxOdds||marketFilter!=='all'||periodFilter!=='all'?'Brak wyników dla tych filtrów':running?'Radar szuka przewagi…':error?'Czekamy na dane źródłowe':'Brak świeżych valuebetów'}</h3><p>{favoriteOnly?'Zapisuj okazje ikoną zakładki. Nieaktualne kursy automatycznie znikają.':running?`Skanujemy ${current||'dostępne sporty'}. Wyniki pojawią się tutaj na bieżąco.`:'Dodatnie EV nie występuje zawsze. Pokazujemy tylko zgodne rynki z aktualnego odczytu.'}</p><button className="empty-link" onClick={()=>query||sport!=='all'||minEv>0||minOdds||maxOdds||marketFilter!=='all'||periodFilter!=='all'?(setQuery(''),setSport('all'),setMinEv(0),setMinOdds(''),setMaxOdds(''),setMarketFilter('all'),setPeriodFilter('all')):setDemo(true)}>{query||sport!=='all'||minEv>0||minOdds||maxOdds||marketFilter!=='all'||periodFilter!=='all'?'Wyczyść filtry':'Zobacz przykładowy widok'}<ArrowUpRight size={14}/></button></div>}
      <div className="table-footer"><span><ShieldCheck size={13}/> Szacowane EV · przed podatkiem i kosztami</span><span>Nieaktualne odczyty są ukrywane po 5 min</span></div>
     </section>
     <aside className="right-column"><section className="panel scanner"><div className="panel-heading"><h2>Status skanera</h2><span className={`status-badge ${running?'live':''}`}>{running?'SKANUJE':error?'BŁĄD':sourceErrors?'CZĘŚCIOWY':'GOTOWY'}</span></div><div className="scan-source"><div className="source-logo betclic-logo">b.</div><div><strong>Betclic Polska</strong><small>Kursy do porównania</small></div><span className="dot"/></div><div className="source-connection"><span/><ArrowDownUp size={14}/><span/></div><div className="scan-source"><div className="source-logo pinnacle-logo">P</div><div><strong>Pinnacle</strong><small>Punkt odniesienia</small></div><span className="dot"/></div><div className="scan-progress"><div><span>Postęp cyklu skanowania</span><b>{finished}/{available||'—'}</b></div><div className="progress-track"><i style={{width:`${available?finished/available*100:0}%`}}/></div></div><div className="market-coverage"><div><span>Odczytane rynki Betclic</span><b>{readMarketCount.toLocaleString('pl-PL')}</b></div><div><span>Zgodne linie obu źródeł</span><b className="mint">{marketCount.toLocaleString('pl-PL')}</b></div><div><span>Brak zgodnej linii referencyjnej</span><b>{missingCount.toLocaleString('pl-PL')}</b></div><div><span>Pełny odczyt sportów</span><b>{done}/{available||'—'}</b></div></div><div className="auto-row"><span><RefreshCw size={14}/> Auto co 5 min</span><button role="switch" aria-checked={auto} aria-label="Automatyczne skanowanie" className={`switch ${auto?'on':''}`} onClick={()=>{setAuto(!auto);autoRef.current=!auto;}}><i/></button></div><p className="scan-footnote">Podczas otwarcia panelu. Kolejny cykl zaczyna się po zakończeniu bieżącego.</p><details className="scan-details"><summary>Porównane rodzaje rynków <ChevronDown size={14}/></summary><div>{Object.entries(marketLabels).map(([kind,label])=><div className="health-row" key={kind}><span>{label}</span><small>{statuses.reduce((sum,h)=>sum+(h.byKind[kind as MarketKind]||0),0)} linii</small></div>)}</div></details><details className="scan-details"><summary>Pokrycie sportów <ChevronDown size={14}/></summary><div>{sports.map(s=>{const h=health[s.key];return <div className="health-row" key={s.key}><span>{s.icon} {s.name}</span><small className={h?.state==='error'?'error-text':''} title={h?.error}>{h?stateLabel[h.state]:'Oczekiwanie'}</small>{h&&h.checked>0&&<p>{h.checked} meczów · {h.markets} zgodnych linii</p>}{h?.error&&<p>{h.error}</p>}</div>;})}</div></details></section>
      <section className="explain-card"><div className="explain-icon"><TrendingUp size={20}/></div><h3>Co oznacza +EV?</h3><p>Kurs Betclic jest wyższy niż kurs fair oszacowany na podstawie Pinnacle.</p><div className="formula">EV = szansa × kurs − 1</div><button onClick={()=>setInfo(true)}>Poznaj metodę <ArrowUpRight size={14}/></button></section>
      <div className="quality-note"><ShieldCheck size={18}/><p>Valuebet może przegrać. EV opisuje szacowaną wartość, a nie pewny wynik.</p></div>
     </aside>
    </div>
    <footer className="footer"><span>EASYBET <span>VALUE RADAR</span></span><p>Betclic PL × Pinnacle · Wersja beta · 18+</p><button onClick={()=>setInfo(true)}>Metoda i zakres danych <ArrowUpRight size={13}/></button></footer>
   </main>
  </div>
  {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
  {modal&&<div className="modal-overlay" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setModal(null)} aria-label="Zamknij szczegóły"><X size={20}/></button><div className="eyebrow">{modal.id.startsWith('demo')?'DANE PRZYKŁADOWE':'SZCZEGÓŁY VALUEBETU'}</div><h2 id="modal-title">{modal.event}</h2><p className="modal-league">{modal.league} · {time(modal.start)}</p><div className="modal-pick"><span>{modal.market}</span><strong>{modal.pick}</strong><small>{modal.settlement}</small></div><div className="modal-stats"><div><span>Kurs Betclic</span><b>{number(modal.odds)}</b></div><div><span>Kurs fair</span><b>{number(modal.fair)}</b></div><div><span>Szacowana szansa</span><b>{number(modal.probability*100,1)}%</b></div></div><div className="calculation"><h3>Kalkulator wartości oczekiwanej</h3><div className="calc-inputs"><label>Stawka (zł)<input type="number" min="0" max="100000" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)))}/></label><label>Koszt od stawki (%)<input type="number" min="0" max="99" value={tax} onChange={e=>setTax(Math.min(99,Math.max(0,Number(e.target.value))))}/></label></div><div className="calc-result"><span>Szacowane EV po kosztach<strong className={ev>0?'mint':'error-text'}>{ev>0?'+':''}{number(ev)}%</strong></span><span>Wartość oczekiwana<strong>{ev>0?'+':''}{number(budget*ev/100)} zł</strong></span></div><p>To średnia modelowa, nie przewidywana wygrana tego kuponu. Uwzględnij faktyczne warunki swojego zakładu.</p></div><div className="modal-actions"><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${modal.event}\n${modal.market}: ${modal.pick}\nBetclic ${number(modal.odds)} · fair ${number(modal.fair)}\nSzacowane EV +${number(modal.ev)}%\n${modal.id.startsWith('demo')?'DANE DEMONSTRACYJNE':`Odczyt: ${new Date(modal.observedAt).toLocaleString('pl-PL')}`}`);message('Skopiowano szczegóły');}catch{message('Przeglądarka nie pozwala skopiować tekstu');}}}><Copy size={15}/>Kopiuj typ</button>{!modal.id.startsWith('demo')&&<a className="primary" href="https://www.betclic.pl/" target="_blank" rel="noopener noreferrer">Otwórz Betclic<ExternalLink size={14}/></a>}</div><p className="modal-disclaimer">Metoda: normalizacja odwrotności wszystkich kursów Pinnacle. Porównanie jest szacunkiem, a kursy mogą się zmienić.</p></section></div>}
  {info&&<div className="modal-overlay" onClick={()=>setInfo(false)}><section className="modal info-modal" role="dialog" aria-modal="true" aria-labelledby="info-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setInfo(false)} aria-label="Zamknij informacje"><X size={20}/></button><span className="eyebrow">JAK DZIAŁA EASYBET</span><h2 id="info-title">Przewaga oparta na porównaniu.</h2><div className="info-step"><b>01</b><div><h3>Dwa niezależne źródła</h3><p>Publiczne kursy Betclic PL i publiczna oferta Pinnacle. Bez płatnego klucza i bez kredytów API. Dostępność źródeł może się zmieniać.</p></div></div><div className="info-step"><b>02</b><div><h3>Ten sam zakład</h3><p>Dopasowanie obu uczestników i czasu rozpoczęcia. Porównujemy zwycięzcę i 1/X/2, sumy, sumy drużyn, handicapy, obie drużyny strzelą oraz rożne. Linia i okres muszą być identyczne. Sumy i handicapy obejmują linie z połówką (np. 2,5 lub −3,5); linie ze zwrotem, dwudrogowy zwycięzca połowy/kwarty z możliwym remisem i handicapy trzydrogowe są pomijane.</p></div></div><div className="info-step"><b>03</b><div><h3>Usunięcie marży i szacowane EV</h3><p>Szansa wyniku = (1 / jego kurs Pinnacle) / suma odwrotności kursów całego rynku. EV = szansa × kurs Betclic − 1. To szacunek rynkowy, nie rzeczywista pewna szansa.</p></div></div><div className="info-step"><b>04</b><div><h3>Wszystkie dostępne sporty</h3><p>Skaner przechodzi całą listę obsługiwanych sportów. Pobieramy dodatkowe kategorie oferty, zachowując osobno połowy, kwarty, sety i tercje. Pokrycie zależy od sportu oraz rynków dostępnych w obu źródłach. Brak rożnych wymaga dokładnie linii 0,5; nie szacujemy jej z innych sum. Sporty bez wspólnej oferty i nierozpoznane rynki są pomijane. Odczyt ma limit 50 stron na sport; przy limicie lub błędzie pokazujemy częściowe pokrycie.</p></div></div><div className="notice"><Activity size={16}/><div>Skanowanie działa podczas otwarcia panelu. Odczyty starsze niż 5 minut znikają. Wysokie anomalie powyżej 25% EV są pomijane do ręcznej weryfikacji.</div></div><p className="modal-disclaimer">Nie zawieramy zakładów. Sprawdź aktualny kurs, zasady rozliczenia oraz podatki i warunki promocji u bukmachera. Valuebet może przegrać całą stawkę.</p></section></div>}
 </div>;
}
